"""descriptive message

Revision ID: c5bc24b42360
Revises: d13d1813c258
Create Date: 2023-07-05 10:15:56.798986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bc24b42360'
down_revision = 'd13d1813c258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_book_awards_award_id_awards')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_awards_book_id_books')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
