"""descriptive message

Revision ID: d5b6395b2d1b
Revises: da339db27390
Create Date: 2023-07-10 11:46:17.467805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b6395b2d1b'
down_revision = 'da339db27390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))
        batch_op.drop_column('rating')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=False))
        batch_op.drop_column('image')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
